### PR TITLE
update lab to v5

### PR DESCRIPTION
**Pull request by bkendall**
also reduced test timeout to 100ms (shouldn't take longer than that)

### CODE REVIEW

**Comment by tjmehta** [comment]
:+1: sweet

**Comment by bkendall** [comment]
(fwiw: this does _not_ enable node `0.12` compatibility)

**Comment by bkendall** [comment]
(also, totally forgot I'm a collaborator on this one - time to (re-)delete my fork)

**Comment by tjmehta** [comment]
looking at the reps, the 12 compatibility must be express related?

**Comment by bkendall** [comment]
I'm leaning towards the `Request` object somehow hurting it? (yes, in express), but I'm not sure...

**Pull request merged**
